sudo: required

language: node_js
node_js:
  - "13.8"
cache:
  directories:
    - "node_modules"

services:
  - docker

install:
  - docker build --cache-from=infrastructureplayground/vuejs:master -t infrastructureplayground/vuejs:master .
  - docker run -d
    --name=vuejs
    infrastructureplayground/vuejs:master

jobs:
  include:
    - stage: Component Unit Testing
      script: docker exec -it vuejs npm run test -t 'Navbar'
    - script: docker exec -it vuejs npm run test -t 'Login'
    - stage: Static Code Analysis
      script: docker exec -it vuejs npm run lint
